version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y zip npm
      - run:
          name: Restore NuGet Packages
          command: dotnet restore ImgStorgeASP.sln
      - run:
          name: Publish Application
          command: |
            ENV_CONFIG_NAME=$(if [ "${CIRCLE_BRANCH}" = "main" ]; then echo "Release"; else echo "Debug"; fi)
            dotnet publish ImgStorgeASP.sln --configuration ${ENV_CONFIG_NAME} --output ImgStorageOutput
      - run:
          name: Create Deployment Package
          command: |
            cd ImgStorageOutput
            zip -r imgstorageasp.zip *
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - ImgStorageOutput/imgstorageasp.zip

  code-scan:
    docker:
      - image: cimg/node:18.16
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Contrast CLI Locally
          command: npm install @contrast/contrast
      - run:
          name: Check if Day is Even
          command: |
            echo "${API_KEY}"
            DAY=$(date +%d)
            if [ $((10#$DAY % 2)) -ne 0 ]; then
              echo "Today is an odd day ($DAY). Skipping code scan."
            else
              echo "Today is an even day ($DAY). Proceeding with code scan."
              npx contrast auth --api-key 2XWW1lpZjal6LUJ66E9lGa19oa1I1ve8 \
              --authorization Y2F0aGFyYXNpc0BtYWlsLnJ1OkxOVE9DWUxLQTRNSTVMTEk= \
              --organization-id 4608bac8-b620-4678-893e-5417667cc262 \
              --host https://ce.contrastsecurity.com
              npx contrast scan --file ImgStorageOutput/imgstorageasp.zip
            fi

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Send Notification
          command: |
            if [ "${CIRCLE_JOB_STATUS}" = "success" ]; then
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d "chat_id=${TELEGRAM_NOTIFICATION_GROUP_ID}" \
                -d "parse_mode=Markdown" \
                --data-urlencode "text=✅ *Build and Scan Workflow* #${CIRCLE_BUILD_NUM} successfully completed."
            else
              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d "chat_id=${TELEGRAM_NOTIFICATION_GROUP_ID}" \
                -d "parse_mode=Markdown" \
                --data-urlencode "text=❌ *Build and Scan Workflow* #${CIRCLE_BUILD_NUM} failed."
            fi

workflows:
  build-and-scan:
    jobs:
      - build
      - code-scan:
          requires:
            - build
          context:
            - TELEGRAM_BOT_TOKEN
