version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0  # Updated to .NET 7 for compatibility
    steps:
      - checkout
      - run:
          name: Restore NuGet Packages
          command: dotnet restore ImgStorgeASP.sln
      - run:
          name: Build Solution
          command: dotnet build ImgStorgeASP.sln --configuration Release
      - run:
          name: Run Tests
          command: dotnet test ImgStorgeASP.sln --configuration Release

  code-scan:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install CodeSec CLI
          command: sudo npm install -g @contrast/contrast
      - run:
          name: Authenticate CodeSec CLI
          command: |
            contrast auth --api-key 2XWW1lpZjal6LUJ66E9lGa19oa1I1ve8 \
              --authorization Y2F0aGFyYXNpc0BtYWlsLnJ1OkxOVE9DWUxLQTRNSTVMTEk= \
              --organization-id 4608bac8-b620-4678-893e-5417667cc262 \
              --host https://ce.contrastsecurity.com
      - run:
          name: Perform SAST Scan
          command: contrast scan --file ImgStorgeASP.sln


workflows:
  build-and-scan:
    jobs:
      - build
      - code-scan:
          requires:
            - build
